
services:
  db:
    image: mysql:8.0
    container_name: employee-management-db
    environment:
      MYSQL_DATABASE: employee_management_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - employee_mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: employee-management-api:latest
    container_name: employee-management-api
    depends_on:
      - db
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-3600000}
    ports:
      - "8081:8081"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: employee-management-phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8082:80"

volumes:
  employee_mysql_data: